import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { trendDiscoveryService } from '../../../app/services';
import { SOURCE_LABELS, TREND_TIER_LABELS } from '../domain/TrendTopic';
import { formatDateTime, formatNumber } from './formatters';
import { publicCategoryLabel, publicScoreVersionLabel, publicSourceEvidenceTitle, publicTopicTitle } from './publicLabels';

export function TrendDetailPage() {
  const { topicId } = useParams();
  const [ready,setReady] = useState(Boolean(trendDiscoveryService.listAll().length));
  const [,setRevision] = useState(0);
  useEffect(()=>{trendDiscoveryService.ensureData().then(()=>setReady(true));},[]);
  const topic = ready && topicId ? trendDiscoveryService.find(topicId) : undefined;
  if (!ready) return <div className="trend-loading">載入展示熱度證據…</div>;
  if (!topic) return <section className="trend-no-results"><h1>找不到主題</h1><Link className="button trend-primary" to="/trends">返回熱門精選</Link></section>;
  const watching = trendDiscoveryService.isWatching(topic.id);
  return <section className="trend-detail-page"><Link className="back-link" to="/trends">← 返回爆紅熱門精選</Link><div className="mock-trend-banner"><strong>展示證據頁</strong><span>以下來源、互動數與時間變化皆為展示資料，不代表真實平台數據。</span></div>
    <header className="trend-detail-hero"><div><div className="trend-card-labels"><span className="trend-category">{publicCategoryLabel(topic.category)}</span><span className={`trend-tier tier-label-${topic.tier}`}>{TREND_TIER_LABELS[topic.tier]}</span>{topic.riskScore>=70&&<span className="risk-flag">警告：高風險</span>}</div><h1>{publicTopicTitle(topic.title)}</h1><p>{topic.summary}</p></div><div className="detail-score" role="img" aria-label={`綜合分數 ${topic.totalScore} 分，滿分 100 分`}><strong>{topic.totalScore}</strong><span>綜合分數</span><small>{publicScoreVersionLabel(topic.scoreVersion)}</small></div></header>
    <div className="detail-actions">{watching?<button className="button secondary" onClick={()=>{trendDiscoveryService.removeFromWatchlist(topic.id);setRevision(v=>v+1);}}>移出觀察</button>:<button className="button trend-primary" onClick={()=>{trendDiscoveryService.addToWatchlist(topic.id);setRevision(v=>v+1);}}>加入觀察</button>}</div>
    <div className="detail-grid"><section className="detail-card score-breakdown"><h2>分數拆解</h2>{topic.scoreDetails.components.map((item)=><div key={item.key} className="score-row"><div><strong>{item.label}</strong><span>原始 {item.rawValue} × 權重 {Math.round(item.weight*100)}%</span></div><b>+{item.points}</b></div>)}<div className="score-total"><span>扣分後總分</span><strong>{topic.totalScore}</strong></div></section>
      <section className="detail-card"><h2>為什麼進入此分級</h2><p className="classification-copy">總分 {topic.totalScore}，目前分級為「{TREND_TIER_LABELS[topic.tier]}」。{topic.status==='high_risk'?'因風險高於門檻，獨立標示高風險。':''}{topic.status==='insufficient_evidence'?'因來源信心不足，不呈現為精確高分。':''}</p><h3>加分原因</h3><ul>{topic.scoreDetails.bonusReasons.length?topic.scoreDetails.bonusReasons.map((item)=><li key={item}>＋ {item}</li>):<li>沒有單項達 80 分。</li>}</ul><h3>扣分原因</h3><ul>{topic.scoreDetails.deductionReasons.length?topic.scoreDetails.deductionReasons.map((item)=><li key={item}>－ {item}</li>):<li>目前沒有主要扣分。</li>}</ul><h3>資料缺少項目</h3><ul>{topic.scoreDetails.missingData.length?topic.scoreDetails.missingData.map((item)=><li key={item}>{item}</li>):<li>目前沒有關鍵缺漏。</li>}</ul></section></div>
    <section className="detail-card source-evidence"><h2>各來源證據</h2><div className="source-evidence-grid">{topic.sourceItems.map((source)=><article key={source.id}><div><span className="mock-data-label">展示資料</span><strong>{SOURCE_LABELS[source.platform]}</strong></div><h3>{publicSourceEvidenceTitle(topic.title, source.platform)}</h3><dl><div><dt>發現時間</dt><dd>{formatDateTime(source.discoveredAt)}</dd></div><div><dt>發布時間</dt><dd>{formatDateTime(source.publishedAt)}</dd></div><div><dt>觀看／互動</dt><dd>{formatNumber(source.engagementCount)}</dd></div><div><dt>增長變化</dt><dd>+{source.growthDelta}%</dd></div><div><dt>來源信心</dt><dd>{source.confidence}%</dd></div></dl><span className="disabled-source-link">原始連結：展示示意，已停用</span></article>)}</div></section>
    <section className="detail-card heat-history"><h2>各平台熱度時間變化</h2>{topic.sourceItems.map((source)=>{const first=source.heatHistory[0]?.value??0;const last=source.heatHistory.at(-1)?.value??0;return <div key={source.id} className="history-row"><strong>{SOURCE_LABELS[source.platform]}</strong><div role="img" aria-label={`${SOURCE_LABELS[source.platform]}熱度由 ${first} 變為 ${last}`}>{source.heatHistory.map((point)=><span key={point.at} style={{height:`${Math.max(8,point.value)}%`}} title={`${formatDateTime(point.at)}：${point.value}`} />)}</div><b>{last}</b><p className="history-summary">熱度由 {first} 變為 {last}，增長 {source.growthDelta}%。</p></div>;})}</section>
    <section className="detail-card risk-panel"><h2>風險與資料品質</h2><div className="risk-metrics"><div><span>風險分數</span><strong>{topic.riskScore}／100</strong></div><div><span>資料信心</span><strong>{topic.sourceConfidence}%</strong></div><div><span>競爭飽和</span><strong>{topic.competitionSaturation}／100</strong></div><div><span>跨平台數</span><strong>{topic.sourcePlatforms.length}</strong></div></div>{topic.isNaturalDisaster&&<p className="natural-warning">自然現象案例：必須通過五項社會共鳴門檻，不能只靠新聞量或搜尋量進入高潛力。</p>}</section>
  </section>;
}
