import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { trendDiscoveryService } from '../../../app/services';
import { SOURCE_LABELS, TREND_TIER_LABELS, type TrendSourceItem } from '../domain/TrendTopic';
import { formatDateTime, formatNumber, growthPresentation } from './formatters';
import { publicCategoryLabel, publicScoreVersionLabel, publicSourceTitle, publicTopicTitle } from './publicLabels';

const numberOrNone=(value:number|null)=>value===null?'來源未提供':formatNumber(value);
const growthLabel=(source:TrendSourceItem)=>growthPresentation(source.growthStatus,source.growthDelta,source.heatHistory).label;

export function TrendDetailPage() {
  const {topicId}=useParams(); const [ready,setReady]=useState(Boolean(trendDiscoveryService.listAll().length)); const [,setRevision]=useState(0);
  useEffect(()=>{trendDiscoveryService.ensureData().then(()=>setReady(true)).catch(()=>setReady(true));},[]);
  const topic=ready&&topicId?trendDiscoveryService.find(topicId):undefined;
  if(!ready)return <div className="trend-loading">載入真實熱度證據…</div>;
  if(!topic)return <section className="trend-no-results"><h1>找不到主題</h1><p>資料可能已更新或目前來源暫時沒有此主題。</p><Link className="button trend-primary" to="/trends">返回熱門精選</Link></section>;
  const watching=trendDiscoveryService.isWatching(topic.id);
  return <section className="trend-detail-page"><Link className="back-link" to="/trends">← 返回爆紅熱門精選</Link><div className="mock-trend-banner real-evidence-banner"><strong>真實來源證據</strong><span>只顯示標題、發布者、時間、原始網址與來源提供的公開統計；不保存新聞全文。</span></div>
    <header className="trend-detail-hero"><div><div className="trend-card-labels"><span className="trend-category">{publicCategoryLabel(topic.category)}</span><span className={`trend-tier tier-label-${topic.tier}`}>{TREND_TIER_LABELS[topic.tier]}</span>{topic.riskScore>=70&&<span className="risk-flag">警告：高風險</span>}{topic.growthStatus==='baseline_pending'&&<span className="evidence-flag">正在建立增速基準</span>}</div><h1>{publicTopicTitle(topic.title)}</h1><p>{topic.summary}</p></div><div className="detail-score" role="img" aria-label={`綜合分數 ${topic.totalScore} 分，滿分 100 分`}><strong>{topic.totalScore}</strong><span>綜合分數</span><small>{publicScoreVersionLabel(topic.scoreVersion)}</small></div></header>
    <div className="detail-actions">{watching?<button className="button secondary" onClick={()=>{trendDiscoveryService.removeFromWatchlist(topic.id);setRevision(v=>v+1);}}>移出觀察</button>:<button className="button trend-primary" onClick={()=>{trendDiscoveryService.addToWatchlist(topic.id);setRevision(v=>v+1);}}>加入觀察</button>}</div>
    <div className="detail-grid"><section className="detail-card score-breakdown"><h2>分數拆解</h2>{topic.scoreDetails.components.map((item)=><div key={item.key} className="score-row"><div><strong>{item.label}</strong><span>原始 {item.rawValue} × 權重 {Math.round(item.weight*100)}%</span></div><b>+{item.points}</b></div>)}<div className="score-total"><span>扣分後總分</span><strong>{topic.totalScore}</strong></div></section>
      <section className="detail-card"><h2>為什麼進入此分級</h2><p className="classification-copy">總分 {topic.totalScore}，目前分級為「{TREND_TIER_LABELS[topic.tier]}」。{topic.status==='high_risk'?'因風險高於門檻，獨立標示高風險。':''}{topic.status==='insufficient_evidence'?'因來源或快照不足，不呈現為精確高分。':''}</p><h3>加分原因</h3><ul>{topic.scoreDetails.bonusReasons.length?topic.scoreDetails.bonusReasons.map((item)=><li key={item}>＋ {item}</li>):<li>沒有單項達 80 分。</li>}</ul><h3>扣分原因</h3><ul>{topic.scoreDetails.deductionReasons.length?topic.scoreDetails.deductionReasons.map((item)=><li key={item}>－ {item}</li>):<li>目前沒有主要扣分。</li>}</ul><h3>資料缺少項目</h3><ul>{topic.scoreDetails.missingData.length?topic.scoreDetails.missingData.map((item)=><li key={item}>{item}</li>):<li>目前沒有關鍵缺漏。</li>}</ul></section></div>
    <section className="detail-card source-evidence"><h2>各來源證據</h2><div className="source-evidence-grid">{topic.sourceItems.map((source)=><article key={source.id}><div><span className="real-data-label">可追溯來源</span><strong>{SOURCE_LABELS[source.platform]}</strong></div><h3>{publicSourceTitle(source.title)}</h3><dl><div><dt>發布者／頻道</dt><dd>{source.publisher}</dd></div><div><dt>發布時間</dt><dd>{formatDateTime(source.publishedAt)}</dd></div><div><dt>系統取得時間</dt><dd>{formatDateTime(source.fetchedAt)}</dd></div><div><dt>觀看</dt><dd>{numberOrNone(source.viewCount)}</dd></div><div><dt>按讚</dt><dd>{numberOrNone(source.likeCount)}</dd></div><div><dt>留言</dt><dd>{numberOrNone(source.commentCount)}</dd></div><div><dt>同主題報導</dt><dd>{source.reportCount===null?'不適用':`${source.reportCount} 筆`}</dd></div><div><dt>增速</dt><dd>{growthLabel(source)}</dd></div><div><dt>來源信心</dt><dd>{source.confidence}%</dd></div></dl><a className="source-link" href={source.originalUrl} target="_blank" rel="noopener noreferrer">查看原始來源 ↗</a></article>)}</div></section>
    <section className="detail-card heat-history"><h2>來源訊號時間變化</h2>{topic.sourceItems.map((source)=>{const last=source.heatHistory.at(-1)?.value??0;const growth=growthPresentation(source.growthStatus,source.growthDelta,source.heatHistory);return <div key={source.id} className="history-row"><strong>{SOURCE_LABELS[source.platform]}</strong><div role="img" aria-label={`${SOURCE_LABELS[source.platform]}：${growth.ariaLabel}`}>{source.heatHistory.map((point)=><span key={point.at} style={{height:`${Math.max(8,point.value)}%`}} title={`${formatDateTime(point.at)}：${point.value}`} />)}</div><b>{last}</b><p className="history-summary">{growth.summary}</p></div>;})}</section>
    <section className="detail-card risk-panel"><h2>風險與資料品質</h2><div className="risk-metrics"><div><span>風險分數</span><strong>{topic.riskScore}／100</strong></div><div><span>資料信心</span><strong>{topic.sourceConfidence}%</strong></div><div><span>競爭飽和</span><strong>{topic.competitionSaturation}／100</strong></div><div><span>跨來源數</span><strong>{topic.sourcePlatforms.length}</strong></div></div>{topic.isNaturalDisaster&&<p className="natural-warning">自然現象必須通過社會討論、情緒共鳴、跨來源與可延伸角度門檻；新聞量本身不會讓它成為高潛力。</p>}</section>
  </section>;
}
