import { trendDiscoveryService } from '../../../app/services';
import { DEFAULT_TREND_WEIGHTS } from '../domain/TrendScoreCalculator';
import { Link } from 'react-router-dom';

export function TrendRulesPage() {
  const rules=trendDiscoveryService.listSavedRules(); const weights=trendDiscoveryService.getWeights();
  return <section className="trend-page"><div className="trend-title-row"><div><div className="trend-date">規則與透明度</div><h1>篩選規則</h1><p>查看目前熱點分數權重與已儲存的 Mock 篩選條件。</p></div></div><div className="subtle-data-note"><strong>目前測試版本</strong><span>熱點分數權重採集中設定；正式管理後台尚未開放。</span></div><section className="detail-card"><h2>熱點分數權重</h2><div className="weights-grid">{Object.entries(weights).map(([key,value])=><div key={key}><span>{weightLabel(key)}</span><strong>{key.includes('Penalty')?`最高扣 ${value} 分`:`${Math.round(Number(value)*100)}%`}</strong></div>)}</div><p className="weight-version">計算版本：trend-score-v1.0.0；目前採用預設設定：{JSON.stringify(weights)===JSON.stringify(DEFAULT_TREND_WEIGHTS)?'是':'否'}</p></section><section className="detail-card"><h2>已儲存篩選規則</h2>{rules.length?<div className="saved-rules">{rules.map((rule)=><article key={rule.id}><strong>{rule.name}</strong><span>{new Intl.DateTimeFormat('zh-TW').format(new Date(rule.savedAt))}</span><p>最低分數 {rule.filters.minimumScore}、分類 {rule.filters.category === 'all'?'全部':rule.filters.category}、排序 {rule.filters.sortBy}</p></article>)}</div>:<section className="trend-no-results actionable-empty"><span className="empty-mark" aria-hidden="true">◇</span><h3>尚未儲存篩選規則</h3><p>到主題搜尋設定常用條件，再選擇「儲存篩選規則」。</p><div><Link className="button card-primary" to="/trends/search">前往主題搜尋</Link></div></section>}</section></section>;
}
const weightLabel=(key:string)=>({currentHeat:'目前熱度',growthRate:'熱度增速',socialResonance:'社會共鳴',crossPlatformResonance:'跨平台共振',freshness:'新鮮度',taiwanRelevance:'台灣相關性',estimatedLifeHours:'預估生命週期',competitionPenaltyMax:'競爭飽和',riskPenaltyMax:'風險',confidencePenaltyMax:'資料信心不足'}[key]??key);
