import { MemoryStorage } from '../../../shared/infrastructure/storage';
import { TrendDiscoveryService, mergeTrendSignals } from '../application/TrendDiscoveryService';
import { TrendScoreCalculator } from '../domain/TrendScoreCalculator';
import { LocalTrendExclusionRepository, LocalTrendFilterRuleRepository, LocalTrendRefreshLogRepository, LocalTrendTopicRepository, LocalTrendWatchlistRepository } from '../infrastructure/LocalTrendRepositories';
import { MOCK_TOPIC_CONFIGS, MockTrendSourceProvider } from '../infrastructure/MockTrendSourceProvider';

function fixture(){ const storage=new MemoryStorage(); const auditEntries:unknown[]=[]; const service=new TrendDiscoveryService(new MockTrendSourceProvider(),new LocalTrendTopicRepository(storage),new LocalTrendWatchlistRepository(storage),new LocalTrendExclusionRepository(storage),new LocalTrendFilterRuleRepository(storage),new LocalTrendRefreshLogRepository(storage),{append:(entry)=>auditEntries.push(entry)}); return {service,auditEntries}; }

describe('Mock資料蒐集與彙整',()=>{
  it('提供22個不同主題、61筆來源訊號與6種來源',async()=>{ const provider=new MockTrendSourceProvider(); const signals=await provider.collectSignals({refreshedAt:new Date().toISOString()}); expect(MOCK_TOPIC_CONFIGS).toHaveLength(22); expect(signals).toHaveLength(61); expect(provider.getProviderNames()).toHaveLength(6); });
  it('相同canonicalKey合併為一個主題並保留來源',async()=>{ const provider=new MockTrendSourceProvider(); const signals=await provider.collectSignals({refreshedAt:new Date().toISOString()}); const same=signals.filter((item)=>item.canonicalKey==='subscription-fatigue'); const merged=mergeTrendSignals(same,new TrendScoreCalculator()); expect(merged).toHaveLength(1); expect(merged[0].sourceItems).toHaveLength(same.length); expect(merged[0].sourcePlatforms.length).toBeGreaterThan(1); });
  it('更新資料會重新彙整、評分、排序並寫入紀錄',async()=>{ const {service,auditEntries}=fixture(); const topics=await service.refresh(new Date()); expect(topics).toHaveLength(MOCK_TOPIC_CONFIGS.length); expect(topics[0].totalScore).toBeGreaterThanOrEqual(topics.at(-1)!.totalScore); expect(service.getLatestRefresh()?.topicCount).toBe(topics.length); expect(auditEntries).toHaveLength(1); });
  it('符合Mock分級數量且包含高風險、證據不足與自然災害案例',async()=>{ const {service}=fixture(); const topics=await service.refresh(); expect(topics.filter((item)=>item.tier==='viral').length).toBeGreaterThanOrEqual(5); expect(topics.filter((item)=>item.tier==='rising').length).toBeGreaterThanOrEqual(5); expect(topics.filter((item)=>item.tier==='observe').length).toBeGreaterThanOrEqual(4); expect(topics.filter((item)=>item.tier==='not_recommended').length).toBeGreaterThanOrEqual(3); expect(topics.filter((item)=>item.status==='high_risk')).toHaveLength(2); expect(topics.filter((item)=>item.status==='insufficient_evidence')).toHaveLength(1); const natural=topics.filter((item)=>item.isNaturalDisaster); expect(natural).toHaveLength(2); expect(natural.every((item)=>item.status!=='high_potential')).toBe(true); });
});
